class ChangeResourcesToStore < ActiveRecord::Migration[5.2]
  def change
    add_reference :blogs, :variation, foreign_key: true
    add_column :variations, :subcategories, :string
    drop_table :spree_addresses, force: :cascade
    drop_table :spree_adjustment_reasons, force: :cascade
    drop_table :spree_adjustments, force: :cascade
    drop_table :spree_assets, force: :cascade
    drop_table :spree_calculators, force: :cascade
    drop_table :spree_cartons, force: :cascade
    drop_table :spree_countries, force: :cascade
    drop_table :spree_credit_cards, force: :cascade
    drop_table :spree_customer_returns, force: :cascade
    drop_table :spree_inventory_units, force: :cascade
    drop_table :spree_line_item_actions, force: :cascade
    drop_table :spree_line_items, force: :cascade
    drop_table :spree_log_entries, force: :cascade
    drop_table :spree_option_type_prototypes, force: :cascade
    drop_table :spree_option_types, force: :cascade
    drop_table :spree_option_values, force: :cascade
    drop_table :spree_option_values_variants, force: :cascade
    drop_table :spree_order_mutexes, force: :cascade
    drop_table :spree_orders, force: :cascade
    drop_table :spree_orders_promotions, force: :cascade
    drop_table :spree_payment_capture_events, force: :cascade
    drop_table :spree_payment_methods, force: :cascade
    drop_table :spree_payments, force: :cascade
    drop_table :spree_preferences, force: :cascade
    drop_table :spree_prices, force: :cascade
    drop_table :spree_product_option_types, force: :cascade
    drop_table :spree_product_promotion_rules, force: :cascade
    drop_table :spree_product_properties, force: :cascade
    drop_table :spree_products, force: :cascade
    drop_table :spree_products_taxons, force: :cascade
    drop_table :spree_promotion_action_line_items, force: :cascade
    drop_table :spree_promotion_actions, force: :cascade
    drop_table :spree_promotion_categories, force: :cascade
    # drop_table :spree_promotion_codes, force: :cascade
    drop_table :spree_promotion_rule_taxons, force: :cascade
    drop_table :spree_promotion_rules, force: :cascade
    drop_table :spree_promotion_rules_users, force: :cascade
    drop_table :spree_promotions, force: :cascade
    drop_table :spree_properties, force: :cascade
    drop_table :spree_property_prototypes, force: :cascade
    drop_table :spree_prototype_taxons, force: :cascade
    drop_table :spree_prototypes, force: :cascade
    drop_table :spree_refund_reasons, force: :cascade
    drop_table :spree_refunds, force: :cascade
    drop_table :spree_reimbursement_credits, force: :cascade
    drop_table :spree_reimbursement_types, force: :cascade
    drop_table :spree_reimbursements, force: :cascade
    drop_table :spree_return_authorizations, force: :cascade
    drop_table :spree_return_items, force: :cascade
    drop_table :spree_return_reasons, force: :cascade
    drop_table :spree_roles, force: :cascade
    drop_table :spree_roles_users, force: :cascade
    drop_table :spree_shipments, force: :cascade
    drop_table :spree_shipping_categories, force: :cascade
    drop_table :spree_shipping_method_categories, force: :cascade
    drop_table :spree_shipping_method_stock_locations, force: :cascade
    drop_table :spree_shipping_method_zones, force: :cascade
    drop_table :spree_shipping_methods, force: :cascade
    drop_table :spree_shipping_rate_taxes, force: :cascade
    drop_table :spree_shipping_rates, force: :cascade
    drop_table :spree_state_changes, force: :cascade
    drop_table :spree_states, force: :cascade
    drop_table :spree_stock_items, force: :cascade
    drop_table :spree_stock_locations, force: :cascade
    drop_table :spree_stock_movements, force: :cascade
    drop_table :spree_store_credit_categories, force: :cascade
    drop_table :spree_store_credit_events, force: :cascade
    drop_table :spree_store_credit_types, force: :cascade
    drop_table :spree_store_credit_update_reasons, force: :cascade
    drop_table :spree_store_credits, force: :cascade
    drop_table :spree_store_payment_methods, force: :cascade
    drop_table :spree_store_shipping_methods, force: :cascade
    drop_table :spree_stores, force: :cascade
    drop_table :spree_tax_categories, force: :cascade
    drop_table :spree_tax_rate_tax_categories, force: :cascade
    drop_table :spree_tax_rates, force: :cascade
    drop_table :spree_taxonomies, force: :cascade
    drop_table :spree_taxons, force: :cascade
    drop_table :spree_unit_cancels, force: :cascade
    drop_table :spree_user_addresses, force: :cascade
    drop_table :spree_user_stock_locations, force: :cascade
    drop_table :spree_users, force: :cascade
    drop_table :spree_variant_property_rule_conditions, force: :cascade
    drop_table :spree_variant_property_rule_values, force: :cascade
    drop_table :spree_variant_property_rules, force: :cascade
    drop_table :spree_variants, force: :cascade
    # drop_table :spree_wallet_payment_sources, force: :cascade
    drop_table :spree_zone_members, force: :cascade
    drop_table :spree_zones, force: :cascade
  end
end
